Ace Asin

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,28 +1,51 @@
 #!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-function indent() {
-	c='s/^/       /'
-	case $(uname) in
-		Darwin) sed -l "$c";;
-		*)      sed -u "$c";;
-	esac
+# fail fast
+set -e
+
+# debug
+# set -x
+
+function print() {
+  echo "-----> $*"
 }
 
-BUILD_DIR="$1"
-SOURCE_DIR="$(dirname $0)/../fonts.tar.gz"
-TARGET_DIR="$BUILD_DIR/.fonts"
-FONTCONFIG_SOURCE_DIR="$(dirname $0)/../fontconfig/."
-FONTCONFIG_TARGET_DIR="$BUILD_DIR/.config/fontconfig/conf.d/"
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
 
-echo "-----> Extracting fonts to $TARGET_DIR"
 
-# set -x
-mkdir -p "$TARGET_DIR"
-tar -xvzf "$SOURCE_DIR" -C "$TARGET_DIR" | indent
-# set +x
+# Default font location
+NOTO_FONT_URL="https://noto-website.storage.googleapis.com/pkgs/Noto-unhinted.zip"
 
-echo "-----> Extracting fontconfig to $FONTCONFIG_TARGET_DIR"
-mkdir -p "$FONTCONFIG_TARGET_DIR"
-cp -a "$FONTCONFIG_SOURCE_DIR" "$FONTCONFIG_TARGET_DIR" | indent
+# attempt to extract the NOTO_FONT_URL parameter form the Heroku configuration vars, fall back to the default version if unavailable
+if [ -d "$ENV_DIR" -a -e "$ENV_DIR/NOTO_FONT_URL" ]; then
+  export NOTO_FONT_URL=$(cat "$ENV_DIR/NOTO_FONT_URL")
+else
+  print "Noto font URL not defined, using $NOTO_FONT_URL."
+  export HUGO_VERSION=$NOTO_FONT_URL
+fi
 
-fc-cache -fv
+
+# attempt to extract the NOTO_FONT_URL parameter form the Heroku configuration vars, fall back to the default version if unavailable
+if [ -d "$ENV_DIR" -a -e "$ENV_DIR/NOTO_CJK_URL" ]; then
+  export NOTO_CJK_URL=$(cat "$ENV_DIR/NOTO_CJK_URL")
+else
+  print "Noto CJK font URL not defined, using $NOTO_CJK_URL."
+  export HUGO_VERSION=$NOTO_CJK_URL
+fi
+
+
+mkdir -p $CACHE_DIR
+
+print "Downloading regular fonts"
+cd $CACHE_DIR
+curl -L --silent $NOTO_FONT_URL > noto-fonts.zip
+unzip -o noto-fonts.zip -d noto-fonts
+rm noto-fonts.zip
+
+print "Copying fonts to app folder"
+mkdir $BUILD_DIR/.fonts
+cp $CACHE_DIR/noto-fonts/* $BUILD_DIR/.fonts/
+cp $CACHE_DIR/noto-cjk-fonts/* $BUILD_DIR/.fonts/
